/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef PERSONAL_BANK_PRIVATE_H
#define PERSONAL_BANK_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.3"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	3
#define COMPANY_NAME	"SILVERSWAG"
#define FILE_VERSION	"1.0.0.3"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Personal Bank"
#define PRODUCT_NAME	"Personal Bank"
#define PRODUCT_VERSION	"1.0.0.3"

#endif /*PERSONAL_BANK_PRIVATE_H*/
